export const FETCH_QUESTIONS_BEGIN = "FETCH_QUESTIONS_BEGIN";
export const FETCH_QUESTIONS_SUCCESS = "FETCH_QUESTIONS_SUCCESS";
export const FETCH_QUESTIONS_FAILURE = "FETCH_QUESTIONS_FAILURE";

// User Selected questions or clicked question
export const GET_ALL_QUESTIONS_CLICKED_By_USER =
  "GET_ALL_QUESTIONS_CLICKED_By_USER";
