










// const questions = [
//   {
//     id: 0,
//     name: "Contains Duplicate",
//     url: "https://leetcode.com/problems/contains-duplicate/",
//     pattern: ["Arrays"],
//     difficulty: "Easy",
//     premium: false,
//     companies: [
//       "Amazon",
//       "Adobe",
//       "Google",
//       "Bloomberg",
//       "Facebook",
//       "Apple",
//       "Microsoft",
//     ],
//   },
//   {
//     id: 1,
//     name: "Missing Number",
//     url: "https://leetcode.com/problems/missing-number/",
//     pattern: ["Arrays", "Bit Manipulation"],
//     difficulty: "Easy",
//     premium: false,
//     companies: ["Microsoft", "Facebook", "Amazon", "Google", "Adobe"],
//   },
//   {
//     id: 2,
//     name: "Find All Numbers Disappeared in an Array",
//     url: "https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array/",
//     pattern: ["Arrays"],
//     difficulty: "Easy",
//     premium: false,
//     companies: ["Facebook", "Amazon"],
//   },
//   {
//     id: 3,
//     name: "Single Number",
//     url: "https://leetcode.com/problems/single-number/",
//     pattern: ["Arrays", "Bit Manipulation"],
//     difficulty: "Easy",
//     premium: false,
//     companies: ["Amazon", "Microsoft", "Adobe"],
//   },
//   {
//     id: 4,
//     name: "Product of Array Except Self",
//     url: "https://leetcode.com/problems/product-of-array-except-self/",
//     pattern: ["Arrays"],
//     difficulty: "Medium",
//     premium: false,
//     companies: [
//       "Facebook",
//       "Amazon",
//       "Asana",
//       "Microsoft",
//       "Apple",
//       "Lyft",
//       "Adobe",
//       "Google",
//       "Uber",
//       "Goldman Sachs",
//       "Oracle",
//     ],
//   },
//   {
//     id: 5,
//     name: "Find the Duplicate Number",
//     url: "https://leetcode.com/problems/find-the-duplicate-number/",
//     pattern: ["Arrays", "Binary Search", "Two Pointers"],
//     difficulty: "Medium",
//     premium: false,
//     companies: [
//       "Google",
//       "Microsoft",
//       "Amazon",
//       "Adobe",
//       "Bloomberg",
//       "Facebook",
//       "Apple",
//     ],
//   },
//   {
//     id: 6,
//     name: "Find All Duplicates in an Array",
//     url: "https://leetcode.com/problems/find-all-duplicates-in-an-array/",
//     pattern: ["Arrays"],
//     difficulty: "Medium",
//     premium: false,
//     companies: ["Amazon", "Google"],
//   },
//   {
//     id: 7,
//     name: "Set Matrix Zeroes",
//     url: "https://leetcode.com/problems/set-matrix-zeroes/",
//     pattern: ["Arrays"],
//     difficulty: "Medium",
//     premium: false,
//     companies: [
//       "Facebook",
//       "Microsoft",
//       "Amazon",
//       "Apple",
//       "Adobe",
//       "Bloomberg",
//       "Oracle",
//     ],
//   },
//   {
//     id: 8,
//     name: "Spiral Matrix",
//     url: "https://leetcode.com/problems/spiral-matrix/",
//     pattern: ["Arrays"],
//     difficulty: "Medium",
//     premium: false,
//     companies: [
//       "Microsoft",
//       "Amazon",
//       "Facebook",
//       "Apple",
//       "Google",
//       "Oracle",
//       "Bloomberg",
//       "Intuit",
//       "Adobe",
//     ],
//   },
//   {
//     id: 9,
//     name: "Rotate Image",
//     url: "https://leetcode.com/problems/rotate-image/",
//     pattern: ["Arrays"],
//     difficulty: "Medium",
//     premium: false,
//     companies: [
//       "Amazon",
//       "Facebook",
//       "Microsoft",
//       "Apple",
//       "Bloomberg",
//       "Uber",
//       "Google",
//     ],
//   },
//   {
//     id: 10,
//     name: "Word Search",
//     url: "https://leetcode.com/problems/word-search/",
//     pattern: ["Backtracking"],
//     difficulty: "Medium",
//     premium: false,
//     companies: [
//       "Amazon",
//       "Microsoft",
//       "Twitter",
//       "Facebook",
//       "Snapchat",
//       "Goldman Sachs",
//       "Google",
//       "Bloomberg",
//       "Apple",
//       "Adobe",
//       "Oracle",
//       "Qualtrics",
//     ],
//   },

//   {
//     id: 11,
//     name: "First Missing Positive",
//     url: "https://leetcode.com/problems/first-missing-positive/",
//     pattern: ["Arrays"],
//     difficulty: "Hard",
//     premium: false,
//     companies: ["Amazon", "Microsoft", "Facebook", "Google", "Adobe", "Apple"],
//   },
//   {
//     id: 12,
//     name: "Longest Consecutive Sequence",
//     url: "https://leetcode.com/problems/longest-consecutive-sequence/",
//     pattern: ["Arrays"],
//     difficulty: "Medium",
//     premium: false,
//     companies: [
//       "Microsoft",
//       "Facebook",
//       "Amazon",
//       "Google",
//       "LinkedIn",
//       "Apple",
//       "Qualtrics",
//       "Goldman Sachs",
//       "Salesforce",
//     ],
//   },

//   {
//     id: 13,
//     name: "Letter Case Permutation",
//     url: "https://leetcode.com/problems/letter-case-permutation/",
//     pattern: ["Backtracking"],
//     difficulty: "Medium",
//     premium: false,
//     companies: ["Microsoft"],
//   },
//   {
//     id: 14,
//     name: "Subsets",
//     url: "https://leetcode.com/problems/subsets/",
//     pattern: ["Backtracking"],
//     difficulty: "Medium",
//     premium: false,
//     companies: [
//       "Facebook",
//       "Amazon",
//       "Google",
//       "Bloomberg",
//       "Goldman Sachs",
//       "Adobe",
//       "Twitter",
//     ],
//   },
//   {
//     id: 15,
//     name: "Subsets II",
//     url: "https://leetcode.com/problems/subsets-ii/",
//     pattern: ["Backtracking"],
//     difficulty: "Medium",
//     premium: false,
//     companies: ["Facebook", "Amazon", "Bloomberg"],
//   },
//   {
//     id: 16,
//     name: "Permutations",
//     url: "https://leetcode.com/problems/permutations/",
//     pattern: ["Backtracking"],
//     difficulty: "Medium",
//     premium: false,
//     companies: [
//       "Amazon",
//       "Facebook",
//       "LinkedIn",
//       "Bloomberg",
//       "Google",
//       "Microsoft",
//       "Adobe",
//       "Apple",
//       "Oracle",
//     ],
//   },
//   {
//     id: 17,
//     name: "Permutations II",
//     url: "https://leetcode.com/problems/permutations-ii/",
//     pattern: ["Backtracking"],
//     difficulty: "Medium",
//     premium: false,
//     companies: ["LinkedIn", "Facebook", "Amazon", "Adobe", "Apple"],
//   },
//   {
//     id: 18,
//     name: "Combinations",
//     url: "https://leetcode.com/problems/combinations/",
//     pattern: ["Backtracking"],
//     difficulty: "Medium",
//     premium: false,
//     companies: ["Google", "Facebook", "Amazon"],
//   },
//   {
//     id: 19,
//     name: "Combination Sum",
//     url: "https://leetcode.com/problems/combination-sum/",
//     pattern: ["Backtracking"],
//     difficulty: "Medium",
//     premium: false,
//     companies: [
//       "Facebook",
//       "Amazon",
//       "Airbnb",
//       "Apple",
//       "Adobe",
//       "Microsoft",
//       "LinkedIn",
//       "Goldman Sachs",
//       "Snapchat",
//       "Salesforce",
//     ],
//   },
//   {
//     id: 20,
//     name: "Combination Sum II",
//     url: "https://leetcode.com/problems/combination-sum-ii/",
//     pattern: ["Backtracking"],
//     difficulty: "Medium",
//     premium: false,
//     companies: ["Facebook", "Amazon"],
//   },
//   {
//     id: 21,
//     name: "Combination Sum III",
//     url: "https://leetcode.com/problems/combination-sum-iii/",
//     pattern: ["Backtracking"],
//     difficulty: "Medium",
//     premium: false,
//     companies: ["Google"],
//   },
//   {
//     id: 22,
//     name: "Generate Parentheses",
//     url: "https://leetcode.com/problems/generate-parentheses/",
//     pattern: ["Backtracking"],
//     difficulty: "Medium",
//     premium: false,
//     companies: [
//       "Amazon",
//       "Facebook",
//       "Microsoft",
//       "Apple",
//       "Bloomberg",
//       "Adobe",
//       "Uber",
//       "Google",
//       "Goldman Sachs",
//     ],
//   },
//   {
//     id: 23,
//     name: "Target Sum",
//     url: "https://leetcode.com/problems/target-sum/",
//     pattern: ["DFS", "Dynamic Programming"],
//     difficulty: "Medium",
//     premium: false,
//     companies: ["Facebook", "Amazon", "Microsoft", "Adobe"],
//   },
//   {
//     id: 24,
//     name: "Palindrome Partitioning",
//     url: "https://leetcode.com/problems/palindrome-partitioning/",
//     pattern: ["Backtracking"],
//     difficulty: "Medium",
//     premium: false,
//     companies: ["Apple"],
//   },
//   {
//     id: 25,
//     name: "Letter Combinations of a Phone Number",
//     url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number/",
//     pattern: ["Backtracking"],
//     difficulty: "Medium",
//     premium: false,
//     companies: [
//       "Amazon",
//       "Microsoft",
//       "Facebook",
//       "Google",
//       "Uber",
//       "Apple",
//       "Adobe",
//       "Twitter",
//       "Bloomberg",
//       "Oracle",
//       "Goldman Sachs",
//       "Snapchat",
//       "Intuit",
//     ],
//   },
// ];

// export { questions };
